cmake_minimum_required(VERSION 4.1)
project(BCP_mid C)

set(CMAKE_C_STANDARD 11)

add_executable(BCP_mid main.c)
add_executable(Q4 main2.c)
add_executable(Q5 main3.c)
add_executable(Q6 main4.c)
add_executable(Q7 main5.c)
add_executable(Q9 main7.c)
add_executable(Q10 main8.c)
add_executable(Q11 main9.c
        main10.c)
